### ISSUE TITLE
gradle-2.13 required?

### ISSUE THREAD

**Issue by bootstraponline** [dampcake/Robolectric-JaCoCo-Sample#1]
`includeNoLocationClasses` is new in gradle 2.13. Is there any info about why this is required and how to make it work on older gradles?

[I found:](https://github.com/gradle/gradle/blob/43737cd3622bfa4a225373b921aa1139cd644aef/subprojects/jacoco/src/main/groovy/org/gradle/testing/jacoco/plugins/JacocoTaskExtension.groovy#L74)

```
/**
     * Whether or not classes without source location should be instrumented.
     * Defaults to {@code false}.
     *
     * This property is only taken into account if the used JaCoCo version
     * supports this option (JaCoCo version >= 0.7.6)
     */
    boolean includeNoLocationClasses = false
```

but that doesn't explain why it's needed for roboeletric.

**Comment by bootstraponline** [comment]
Ok, nevermind. I found the [upstream bug](https://github.com/robolectric/robolectric/issues/2230) with the details.

Thanks for posting this sample!

**Comment by dampcake** [comment]
This was originally used to show the issue of JaCoCo 0.7.3-0.7.5 not reporting coverage correctly, but I updated it when the bugs were closed. Unfortunately yes gradle 2.13 is required, unless you specify a version of JaCoCo of at most 0.7.2.

I should probably add a README.md to explain :P

**Comment by bootstraponline** [comment]
> I should probably add a README.md to explain :P

:+1:
